### ISSUE TITLE
To change the colours of the walls and floor would I have to edit on mesh.js?

### ISSUE THREAD

**Issue by maielamin** [ClementCariou/virtual-art-gallery#10]

**Comment by ClementCariou** [comment]
Yes, you will have to modify the fragment shader in mesh.js.

**Comment by maielamin** [comment]
I figured out how to do this but it does involve a couple steps. In the mesh.js folder I commented Line 96: totalLight = pow(totalLight, vec3(1.0/2.2)); Copied and pasted Line 96: totalLight = pow(totalLight, vec3(,,); (deleting what was inside the brackets of vec3). In these brackets you have to add a GSL vec 3 code which consists of 3 digits. Using coolors.co to look up hex codes for a colour I converted them into GSL vec 3 using this website https://airtightinteractive.com/util/hex-to-glsl/. Copying and pasting the code into the brackets. 

*When looking for a colour find the complimentary colour on a colour wheel and look for that hex code. For example, Dark purple #2B061E will give you a green coloured room
![warm-cool-colors](https://user-images.githubusercontent.com/43281220/107127717-737da600-68d1-11eb-8829-64b4f01e8539.jpeg)

<img width="1368" alt="Dark purple #2B061E" src="https://user-images.githubusercontent.com/43281220/107127727-7d9fa480-68d1-11eb-9af4-c8e474eb8e27.png">
