### ISSUE TITLE
Is it possible to add sound?

### ISSUE THREAD

**Issue by maielamin** [ClementCariou/virtual-art-gallery#11]
I have tried the usual methods of adding sound to html and javascript neither of them have worked. Do you know a way of doing it when the website loads or as you get close to an art piece?

**Comment by ClementCariou** [comment]
Please don't ask questions unrelated to this project. Just [google it](https://letmegooglethat.com/?q=javascript+sound) or ask on [stackoverflow](https://stackoverflow.com/).
