### ISSUE TITLE
Problem changing painting titles locally

### ISSUE THREAD

**Issue by seventheefs** [ClementCariou/virtual-art-gallery#12]
Hi,
I've tried to upload my own images by adding them in the images folder and it worked perfectly. My problem is that when I re-build the project, all the modifications that I make in the "images.json" file get erased. I've also tried to edit that file after re-building but i still can't get the titles changed.

**Comment by ClementCariou** [comment]
By default image.json is generated by the script generateList.js. You can remove prestart and prebuild in package.json.
