### ISSUE TITLE
hilbert curve smaller order

### ISSUE THREAD

**Issue by mfused** [ClementCariou/virtual-art-gallery#15]
hello,
the most amazing gallery we found open-sourced yet!
congratulations! regarding map.js, could you pls help us with
mapping it to hilbert curve of smaller order, 2 or 4?!
it would be interesting for everyone with smaller amount of images.
thank you!

**Comment by ClementCariou** [comment]
Hello,

Thank you for the compliments. 🙂
The order of the hilbert curve is set at line 202 in map.js, the argument n corresponds to this parameter. You just have to change n=7 into n=4.

I hope I helped.
