### ISSUE TITLE
description text for local images 

### ISSUE THREAD

**Issue by mfused** [ClementCariou/virtual-art-gallery#16]
thanx for replying on hilibert curve question, that helped a lot.

Paintings from Art Institute Chicago have text descriptions below them.

i was wondering if adding description text
for images from local folder is already implemented?
i am reading text.js and i don't see where to put my text 
for textCanvas. sorry if i am missing something.
everything is so smooth and done dynamically, so i though
i better ask you first.
thank you

**Comment by ClementCariou** [comment]
You just have to modify the API.

Here is an explanation of the process :
Whenever a painting is loaded, image.js asks the API for the title and image. The init() function of text.js is called in order to render the text into a texture. The function loadPainting() of placement.js sets the painting position. Then, every frame, the batch of visible paintings is drawn in painting.js and text.js.

**Comment by mfused** [comment]
thank you, i thought so. 
so, in local.js:
  fetchImage: async function (obj, advicedResolution) {
        const url = "images/" + obj.file;
        const blob = await fetch(url).then(res => res.blob());
        return {
            title: obj.title,
            image: blob

i write:
  title: obj.title + " - " + obj.artist_title,

and that's it? but from which file it scoops that description (obj.artist_title)?

thank you!

**Comment by ClementCariou** [comment]
To make things simple, using the local api, the name of the image file is displayed by default. The genlist.js script generates a json file containing the list of paintings with the titles and image file names. It can be modified manually with the prestart line removed from the package.json to avoid overwriting the json file.

**Comment by mfused** [comment]
ah, ok, thank you so much!!!!!!

**Comment by ClementCariou** [comment]
> thank you, i thought so. 
> so, in local.js:
>   fetchImage: async function (obj, advicedResolution) {
>         const url = "images/" + obj.file;
>         const blob = await fetch(url).then(res => res.blob());
>         return {
>             title: obj.title,
>             image: blob
> 
> i write:
>   title: obj.title + " - " + obj.artist_title,
> 
> and that's it? but from which file it scoops that description (obj.artist_title)?
> 
> thank you!

The obj argument is whatever elements you return in fetchList. In the local API example it's the same objects as in images.json with the additional variable image_id because of the mapping.
