### ISSUE TITLE
How to change the Gallery structure?

### ISSUE THREAD

**Issue by harshitsharma03** [ClementCariou/virtual-art-gallery#24]
Hi There, 

You are super awesome boss, greatest open source art gallery I saw till now. 

Possible if you can help me out in just one thing. 

How can I change a structure ? Just wanted to add one wall in between just once so as to show a welcome message? How can I do so ?

Please advise

**Comment by ClementCariou** [comment]
Hello,

I have to warn you, this project isn't designed to have this kind of changes.
The wall structure is generated by map.js when the page loads. Multiple data are generated :
- geometry to render
- painting placements
- callback functions for physics and culling
The walls are then rendered in index.js ("drawMap" calls) using the shader defined in mesh.js.
If you want to render new walls, I suggest you to make your own geometry and render it with the same shader. This way you will be able to change or remove it at runtime. If you want the physical boundaries to work as well, you will have to overwrite the getGridSegments and getGridParts as well.

A simpler and less sexy solution would be to show your welcome message in a modal.

Good luck 🙂

**Comment by harshitsharma03** [comment]
Hi Sir, Thanks for the update. Possible if you can suggest any other example. where I can try looking into it.??
