### ISSUE TITLE
Need help with some small tweak

### ISSUE THREAD

**Issue by harshitsharma0003** [ClementCariou/virtual-art-gallery#27]
Hi Developer,. 

Really did a great job. Hats off to you. Just one tweak I wanted to do as its my college project. Can I have navigation key somehow any tweak on the left bottom, I can make them work via javascript but not able to place it. I added drawImage many place but not working. Can you please help.

**Comment by ClementCariou** [comment]
You can't draw on the same canvas 2d and webgl content. Place it in a separate canvas on top of the main canvas.

**Comment by harshitsharma0003** [comment]
Thanks for the reply, I am just a newb in this webgl and canvas2d and I have already submitted my project name as Virtual Gallery. Can you please help me out where and in which file I should add that. Please
