### ISSUE TITLE
Gallery goes upside down when going back

### ISSUE THREAD

**Issue by bootkernel** [ClementCariou/virtual-art-gallery#29]
First of all, such an amazing work! I've started using it in one of my projects. 

I've noticed a bug as I was walking around the gallery (attaching a screenshot):

![Bug](https://user-images.githubusercontent.com/33711869/160362488-7597e51b-109a-4cd8-bdba-2b5f978f2ec7.png)

This happens when I go towards the end and try to come back where I started or even sometimes in the middle when looking up. I'm also attaching a short video of this here:

https://user-images.githubusercontent.com/33711869/160363966-7e9e25d7-97e8-40f6-b904-4fdb20c670e6.mp4

This is in Chrome. I've not checked it in other browsers.

**Comment by mathcodes** [comment]
It seems to happen whenever you walk right up to a wall, then turn around.

**Comment by khbabah** [comment]
@bootkernel did you get a solution for this issue ? @ClementCariou are you working on this ? and thanks for this amazing work !

**Comment by bootkernel** [comment]
> @bootkernel did you get a solution for this issue ? 

No I wasn't able to find a solution for this.

**Comment by ClementCariou** [comment]
The problem is fixed.
