### ISSUE TITLE
Wall shadow

### ISSUE THREAD

**Issue by adeprez** [ClementCariou/virtual-art-gallery#33]
Bonjour, tout d'abord merci pour votre travail sur ce beau projet open-source. Je cherche à variabiliser celui-ci afin de permettre la modification de certains éléments, notamment les dimensions de la map.

J'ai pu constater que des variables permettent de jouer facilement sur l'aspect des murs ; toutefois j'ai du mal à trouver quelle portion de code est en charge d'appliquer l'effet d'ombre sur la partie supérieure des murs.

En effet, s'il est possible de modifier leur hauteur grâce à la variable `mapHeight` dans `map.js`, visuellement le plafond semble être à la même hauteur en raison de l'effet d'ombre dont la couleur se rapproche de celle du plafond.

Je vous serais reconnaissant s'il vous était possible de m'aiguiller sur la portion de code en charge du rendu de cette ombre.

Merci !

![image](https://github.com/ClementCariou/virtual-art-gallery/assets/2982153/de4935bd-4004-4d28-a5e0-f51245e4a302)

**Comment by adeprez** [comment]
J'ai fini par trouver, dans le main regl de `mesh.js` :)

![image](https://github.com/ClementCariou/virtual-art-gallery/assets/2982153/5eb4c76d-1afe-4869-b474-6192cc6f3611)

**Comment by ClementCariou** [comment]
Oui, pardon je n'ai pas eu le temps de te répondre.
