### ISSUE TITLE
Zoom on picture on click

### ISSUE THREAD

**Issue by benjyazoulay** [ClementCariou/virtual-art-gallery#37]
Bonjour Clément, ce projet est vraiment formidable. Est-ce que tu crois qu'il y aurait moyen de rajouter une option qui zoome sur le tableau quand on clique dessus ? Sinon tu pourrais me dire quel fichier il faudrait modifier ?
Immense merci pour ce travail, c'est génial !

**Comment by ClementCariou** [comment]
Le code de déplacement est dans le fichier fps.js. Sur téléphone, un mode de déplacement particulier est implémenté : lorsque tu cliques sur un tableau, la vue se déplace automatiquement devant le tableau.

**Comment by ClementCariou** [comment]
Pour implémenter ta feature, tu peux écouter les évènements de cliques et réutiliser le code de raycast sur les murs dans `pointer.on("data",` après libre à toi d'ajuster le zoom pour que le tableau soit visible sur tout l'écran.

**Comment by benjyazoulay** [comment]
Génial merci beaucoup !
