### ISSUE TITLE
after i build the app, how can i deploy it to netlify and why it is all blank image and black gallery background

### ISSUE THREAD

**Issue by 25920** [ClementCariou/virtual-art-gallery#38]
after i build the app, how can i deploy it to netlify and why it is all blank image and black gallery background.

after i ran the build, i open the build . html on firefox only black gallery wall with white canvas on the app, why what happened?

**Comment by ClementCariou** [comment]
Opening the build HTML in the browser wont let the app fetch the images. You have to host the project using a web server.

**Comment by 25920** [comment]
may i ask where did you host it?

**Comment by ClementCariou** [comment]
I used Github Page to host it publicly. You can look at the github action config of this project.

**Comment by 25920** [comment]
**thxxxxx**
