### ISSUE TITLE
How to upload own art/images?

### ISSUE THREAD

**Issue by jakesullyneytiri** [ClementCariou/virtual-art-gallery#4]
Could you add a guide how to add your own art/images to this?

Since right now you haven't written anywhere how to do it and i'm clueless what todo to get my own art/images into this art gallery,

**Comment by maielamin** [comment]
uncommenting and commenting the text presented doesn't do anything you will have to find the text fetch images on the build.html file and it change it there too I'm still trying to figure it out

**Comment by ClementCariou** [comment]
The build.html is a generated file. You need to run `npm start` to run the dev server or `npm build` to build the build.html.

**Comment by jakesullyneytiri** [comment]
> The build.html is a generated file. You need to run `npm start` to run the dev server or `npm build` to build the build.html.

Well that does not fully answer my question, could you make proper tutorial on how to add own images? by runing these commands does not solve my problem. Since 1. I don't know what to change in coding to get it to read my own images instead from some API stuff. I want to be able to tell it to read images from a folder or something which when doing npm build it will build file so it can read images i have in a folder.

**Comment by maielamin** [comment]
I deleted the original build.html in the folder and followed the readme.md to test with the example images so I uncommented the example script and commented the top half. It works but when the pictures don't display in the frames. Why could this be?

**Comment by ClementCariou** [comment]
The method I have posted a week ago was temporary. Now you need to follow these steps to display your images :

1. Setup the project
2. Put your images into the folder images
3. Modify the file [images/images.json](images/images.json) (automated soon)
4. Depending on what you want to do
a. Run the server ```npm start```, go to the address displayed in the terminal
b. Build the project ```npm build```, and host the build.html file and the image folder
5. append ```?api=local``` to the URL (you can set to default in [api/api.js](api/api.js))

> I deleted the original build.html in the folder and followed the readme.md to test with the example images so I uncommented the example script and commented the top half. It works but the pictures don't display in the frames and neither does the title. Why could this be?

The file protocole doesn't allow fetch queries, you have to use host it or use the dev server. If it doesn't solve it, send me the logs.

**Comment by jakesullyneytiri** [comment]
> The method I have posted a week ago was temporary. Now you need to follow these steps to display your images :
> 
> 1. Setup the project
> 2. Put your images into the folder images
> 3. Modify the file [images/images.json](images/images.json) (automated soon)
> 4. Depending on what you want to do
>    a. Run the server `npm start`, go to the address displayed in the terminal
>    b. Build the project `npm build`, and host the build.html file and the image folder
> 5. append `?api=local` to the URL (you can set to default in [api/api.js](api/api.js))
> 
> > I deleted the original build.html in the folder and followed the readme.md to test with the example images so I uncommented the example script and commented the top half. It works but the pictures don't display in the frames and neither does the title. Why could this be?
> 
> The file protocole doesn't allow fetch queries, you have to use host it or use the dev server. If it doesn't solve it, send me the logs.

i cannot find a line as ?api=local but i found line named local: require("./local") in folder api/api.js so what exactly do i do there? Do i put http:// url or what?

**Comment by maielamin** [comment]
<img width="1368" alt="Screenshot 2021-01-31 at 18 57 15" src="https://user-images.githubusercontent.com/43281220/106390301-2301d680-6401-11eb-85e5-43e07721049c.png">

Unfortunately, the pictures don't show but I think what you've created is great!

**Comment by jakesullyneytiri** [comment]
> <img alt="Screenshot 2021-01-31 at 18 57 15" width="1368" src="https://user-images.githubusercontent.com/43281220/106390301-2301d680-6401-11eb-85e5-43e07721049c.png">
> 
> Unfortunately, the pictures don't show but I think what you've created is great!

Reason why they don't show is 1. they must be PNG format, 2.Reload page with ctrl and F5 or CMD F5 or w.e it is on mac.

**Comment by maielamin** [comment]
> > <img alt="Screenshot 2021-01-31 at 18 57 15" width="1368" src="https://user-images.githubusercontent.com/43281220/106390301-2301d680-6401-11eb-85e5-43e07721049c.png">
> > Unfortunately, the pictures don't show but I think what you've created is great!
> 
> Reason why they don't show is 1. they must be PNG format, 2.Reload page with ctrl and F5 or CMD F5 or w.e it is on mac.

I'm afraid neither of them resolve the issue

**Comment by jakesullyneytiri** [comment]
> > > <img alt="Screenshot 2021-01-31 at 18 57 15" width="1368" src="https://user-images.githubusercontent.com/43281220/106390301-2301d680-6401-11eb-85e5-43e07721049c.png">
> > > Unfortunately, the pictures don't show but I think what you've created is great!
> > 
> > 
> > Reason why they don't show is 1. they must be PNG format, 2.Reload page with ctrl and F5 or CMD F5 or w.e it is on mac.
> 
> I'm afraid neither of them resolve the issue

well for me it worked, also make sure you run npm build after changes as well.

**Comment by maielamin** [comment]
> > > > <img alt="Screenshot 2021-01-31 at 18 57 15" width="1368" src="https://user-images.githubusercontent.com/43281220/106390301-2301d680-6401-11eb-85e5-43e07721049c.png">
> > > > Unfortunately, the pictures don't show but I think what you've created is great!
> > > 
> > > 
> > > Reason why they don't show is 1. they must be PNG format, 2.Reload page with ctrl and F5 or CMD F5 or w.e it is on mac.
> > 
> > 
> > I'm afraid neither of them resolve the issue
> 
> well for me it worked, also make sure you run npm build after changes as well.

I've followed your instructions but it's the same problem unfortunately

**Comment by ClementCariou** [comment]
> > > > > <img alt="Screenshot 2021-01-31 at 18 57 15" width="1368" src="https://user-images.githubusercontent.com/43281220/106390301-2301d680-6401-11eb-85e5-43e07721049c.png">
> > > > > Unfortunately, the pictures don't show but I think what you've created is great!
> > > > 
> > > > 
> > > > Reason why they don't show is 1. they must be PNG format, 2.Reload page with ctrl and F5 or CMD F5 or w.e it is on mac.
> > > 
> > > 
> > > I'm afraid neither of them resolve the issue
> > 
> > 
> > well for me it worked, also make sure you run npm build after changes as well.
> 
> I've followed your instructions but it's the same problem unfortunately

Openning the build.html with you web browser directly isn't supported. You have to host the website (with apache or express for example) or run the dev webserver ```npm start``` and open the hosted address.
