### ISSUE TITLE
Image displaying order from local API and problem with images repeating

### ISSUE THREAD

**Issue by lukaszkaczorowski** [ClementCariou/virtual-art-gallery#9]
Hi,

Is there any possibility to put images in specific order? I've tried to supply image_id in images.json but it doesn't do anything.
Before last update images supplied with API were shown just once, but now images repeats itself. For example if loading 5 images from local API it shows them in loop till the galery is run out of space.

**Comment by ClementCariou** [comment]
Yeah, I did that for testing, you can use the old version of [local.js](https://github.com/ClementCariou/virtual-art-gallery/blob/f6fc0a199f5fe84e687ba30d9744f610102a09fa/api/local.js) to get non-repeating images.

**Comment by ClementCariou** [comment]
I fixed it.

**Comment by ClementCariou** [comment]
The order alternates between left and right but isn't very precise or controllable.   It's designed to handle dynamic image loading correctly.

**Comment by lukaszkaczorowski** [comment]
Thanks a lot, I get it now. I have one more question, is it possible to set the same map for all visitors? Currently after each page refresh map is changing. If it's possible I could just try to predict location of paintings on wall and make some adjustment based on that.

**Comment by ClementCariou** [comment]
Yeah you can change Math.random() with a seeded random number generator in [map.js](src/map.js) at line 55.
